### ISSUE TITLE
review / refresh documentation links (and more?)

### ISSUE THREAD

**Issue by raiph** [perl6/perl6-examples#44]
The examples left a strongly negative impression for at least one person expecting doc that's beyond the speculation stage. See http://www.perlmonks.org/?node_id=1163279 for the unfortunate impact of the first example in the first category. I've fixed that particular example but I'm filing this issue with the intent we review and refresh at least the documentation links in all examples (and perhaps review/refresh more as we go? please comment here if you've thought of something worth doing at the same time).

**Comment by stmuk** [comment]
That example shouldn't point at the design/spec pages  but rather at
http://docs.perl6.org/language/operators#Cross_Operators.

Other refs should also be fixed in

categories/best-of-rosettacode/24-game.pl

categories/best-of-rosettacode/ackermann-function.pl

categories/best-of-rosettacode/arbitrary-precision-integers.pl

categories/best-of-rosettacode/balanced-brackets.pl

categories/best-of-rosettacode/last-fridays-of-year.pl

categories/other/combinations.pl

I can fix this in a few hours times if it still needs doing...

S


On 22 May 2016 at 22:06, raiph <notifications@github.com> wrote:

> The examples left a strongly negative impression for at least one person
> expecting doc that's beyond the speculation stage. See
> http://www.perlmonks.org/?node_id=1163279 for the unfortunate impact of
> the first example in the first category. I've fixed that particular example
> but I'm filing this issue with the intent we review and refresh at least
> the documentation links in all examples (and perhaps review/refresh more as
> we go? please comment here if you've thought of something worth doing at
> the same time).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/perl6-examples/issues/44>
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by raiph** [comment]
I've updated 100-doors, 24-game and ackermann-function. I didn't see anything to update for a couple of the files you listed so I've decided to pause; maybe I'm missing some other stuff that needs to change?

**Comment by stmuk** [comment]
Thanks! I altered a few more links and removed a broken link.

I think this can probably be closed.

**Comment by raiph** [comment]
Thanks. :)
